//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyYF.YuanXin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EditOnEnter")]
        public global::System.Windows.Forms.DataGridViewEditMode myEdit {
            get {
                return ((global::System.Windows.Forms.DataGridViewEditMode)(this["myEdit"]));
            }
            set {
                this["myEdit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string HappyYFConnectionString {
            get {
                return ((string)(this["HappyYFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string HappyYF_YXConnectionString {
            get {
                return ((string)(this["HappyYF_YXConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Max Pool Size=150;Connect Timeout=0")]
        public string HappyYHConnectionString {
            get {
                return ((string)(this["HappyYHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string HappyYF_XDConnectionString {
            get {
                return ((string)(this["HappyYF_XDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string HappyYf_HSConnectionString {
            get {
                return ((string)(this["HappyYf_HSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.")]
        public string happyyf_lyConnectionString {
            get {
                return ((string)(this["happyyf_lyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string happyyf_lyConnectionString1 {
            get {
                return ((string)(this["happyyf_lyConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string happyyf_lyConnectionString2 {
            get {
                return ((string)(this["happyyf_lyConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string happyyf_lyConnectionString3 {
            get {
                return ((string)(this["happyyf_lyConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.9,3059;Initial Catalog=happyyf_ly;Persist Security Info=Tru" +
            "e;User ID=sa;Password=jm123456.;Connect Timeout=0")]
        public string happyyf_lyConnectionString4 {
            get {
                return ((string)(this["happyyf_lyConnectionString4"]));
            }
        }
    }
}
